### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by sachinshajan** [N3TC4T/Hotel-Management-System-#9]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function CI_Loader::is_loaded(), 0 passed in C:\xampp\htdocs\hms\system\core\Loader.php on line 150 and exactly 1 expected in C:\xampp\htdocs\hms\system\core\Loader.php:171 Stack trace: #0 C:\xampp\htdocs\hms\system\core\Loader.php(150): CI_Loader->is_loaded() #1 C:\xampp\htdocs\hms\system\core\Controller.php(51): CI_Loader->initialize() #2 C:\xampp\htdocs\hms\application\controllers\admin_home.php(11): CI_Controller->__construct() #3 C:\xampp\htdocs\hms\system\core\CodeIgniter.php(308): Admin_home->__construct() #4 C:\xampp\htdocs\hms\index.php(202): require_once('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\hms\system\core\Loader.php on line 171

I am new to php and also codeigniter,can you help me sir,please i was able to fix 2 errors biut this is not giving me any idea,please help

**Comment by Duc2310** [comment]
ngu loi y het tao
